    import {ns } from './condense'
    export default ns([
          3, // OSC1_WAVEFORM
          63, // OSC1_VOL
          128, // OSC1_SEMI
          36, // OSC1_XENV
          0, // OSC2_WAVEFORM
          166, // OSC2_VOL
          112, // OSC2_SEMI
          181, // OSC2_DETUNE
          25, // OSC2_XENV
          3, // NOISE_VOL
          4, // ENV_ATTACK
          4, // ENV_SUSTAIN
          67, // ENV_RELEASE
          32, // ENV_EXP_DECAY
          156, // ARP_CHORD
          1, // ARP_SPEED
          0, // LFO_WAVEFORM
          195, // LFO_AMT
          6, // LFO_FREQ
          0, // LFO_FX_FREQ
          3, // FX_FILTER
          51, // FX_FREQ
          186, // FX_RESONANCE
          127, // FX_DIST
          212, // FX_DRIVE
          0, // FX_PAN_AMT
          2, // FX_PAN_FREQ
          29, // FX_DELAY_AMT
          3 // FX_DELAY_TIME
          ], [135, 125])